# Site settings
title: "Dae Young Kim"
description: "AI Research Scientist | Expertise in LLMs & Knowledge Graphs"
# baseurl: "/textlog" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "Kim, Dae Young"

# Build settings
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
