name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main # Trigger workflow on pushes to the main branch
  workflow_dispatch: # Allow manual triggers from the Actions tab

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1' # Use Ruby 3.4.1
        bundler-cache: true # Cache gems to speed up builds

    - name: Install dependencies
      run: |
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
        publish_dir: ./_site # Path to the built site
